### ISSUE TITLE
Improve the system stability

### ISSUE THREAD

**Issue by supereagle** [caicloud/cyclone#249]
Currently, the system is a little complex, so the stability is not good enough. The server will hang sometimes which is reported in #232. So it is urgently needed to improve the stability.

ToDo Lists:
- [x] #232 Cyclone server hangs sometimes
- [x] #203 Clean up useless components, like clair and postgres.
- [x] #252 Worker can not get event from Cyclone server
- [x] #190 Can not get log through websocket when pipeline is running
- [ ] Worker management
  - [x] #258 Pods with error is not cleaned up when perform pipeline
- [ ] ...

**Comment by supereagle** [comment]
System stability has been improved after refactor.
/close
